name: burtonts
favicon: null
layout_spectrum: 0.3153
typography_spectrum: 0.77667
title: burtonts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030305'
    - '#f4ede3'
    - '#463120'
    - '#9c673f'
    - '#dca378'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.10452441545203328
  rhythmicContrast: 0.5
purpose: []
