name: burtonts
favicon: null
layout_spectrum: 0.3153
typography_spectrum: 0.77667
title: burtonts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#629abb'
    - '#fcfbf6'
    - '#b6b5bd'
    - '#4b5b68'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.10452441545203328
  rhythmicContrast: 0.5
purpose: []
